language: node_js
services: docker
node_js: 6.10

env:
  global:

    - AWS_ACCESS_KEY_ID=AKIAIY72BYOTX7AYCKAA
    - AWS_DEFAULT_REGION=ap-southeast-2

    - LAMBDA_NAME=securityGroupIpPoker
    - LAMBDA_DESCRIPTION="Pokes a hole in an AWS security group for temporary access from an authorised IP."
    - LAMBDA_TIMEOUT=15
    - LAMBDA_ROLE=arn:aws:iam::873114526714:role/genericLambdaEC2Manager

    - LAMBDA_RUNTIME=node6.10
    - LAMBDA_MODULE=index
    - LAMBDA_HANDLER=handler

    # AWS_SECRET_ACCESS_KEY
    - secure: OHIZQNnxsWI07TUgnP/JnL8PZkpjoYRag9/YcYPx2Sk+KDg8IP2AEYlRt7+WUco6p0NxCIwALt1rIq3/zbUJ/qtiK0tDRi+R38Syj5cD2tESVI4U2DghGF+BzQsJYVDIjDV8lBnAo13eLeRaKSv2/tQL1G/txOYT7ECwnka/D3JoXd4XLXQDcaUxswuWlQKTHfzaG2xdVYQAaVuU8ODf/7D/Y3SIeBxZWIGXvo8WO77nPdEkYffQPFfwj4wYuyAiJxm2JdgYSjhXHkJ2g2y3k4x34x/1vcskcHGKrJ90hgsvwdFpIoqmyEeoac7SibUcnssViY15nn6zUnKITD2BS2qPZwAfAiJTb8jT59sWFbazDI/smcyrUeYPr3m4IWEyc989U9w7Dh+YhYceCX+BOqdI1huG/5niehxWwl/41H1appChZH7p8dUYMzQtVPCOuj1pW3BdQeTK1W8ZfPZuCyiJqZPnRxNTRTTsSJ9oZxgzJr0CZBi0tZemJlD7e+ZSV9sTVe2L5hJ7Q2Niw4pXS/dKRaCTdaubYolA5kb8Az509sjUYC8IAxvSgfrtXkE4ve1aEERM21ihJOCxHeZ5VPMimRqjPj5v6sVBOGQmBDonWdMQMN3SR2VayKnSdviQI1BtNDy/Rti2dm4t7NnJ4vu+swj5/KrF0BA5vphaDLw=

cache:
  yarn: true
  directories:
    - node_modules

install: yarn

script:
  - yarn lint
  - yarn test

before_deploy:
  - yarn remove aws-sdk
  - rm -rf coverage node_modules .*rc.js
  - yarn --prod

deploy:

  - on:
      branch: master
    publish: true

    provider: lambda
    function_name: $LAMBDA_NAME
    region: $AWS_DEFAULT_REGION
    role: $LAMBDA_ROLE
    description: $LAMBDA_DESCRIPTION
    runtime: $LAMBDA_RUNTIME
    timeout: $LAMBDA_TIMEOUT
    module_name: $LAMBDA_MODULE
    handler_name: $LAMBDA_HANDLER
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true

notifications:
  email: false
  webhooks:
    urls:
      - https://chr-cicd.herokuapp.com/hooks/travis.php
    on_start: always
